source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'NMPopUpViewSwift_Example' do
    pod 'NMPopUpViewSwift'
    
    target 'NMPopUpViewSwift_Tests' do
        inherit! :search_paths
        pod 'NMPopUpViewSwift'
    end
end
